# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      serviceprinciple:
        description: 'Service principle'
        default: 'Please fill'
        required: true
        
      Id:
        description: 'Tenant Id'
        required: true
        
      PR:
        type: choice
        default: 'true'
        options:
          - 'true'
          - 'false'
        required: true
#         type: choice
#         default: 'true'
#         options: 
#         - 'true'
#         - 'false'


jobs:
  
  Workflow_Input:
    
    runs-on: ubuntu-latest
    steps:
    - name: Service Principle
      run: echo "${{ github.event.inputs.serviceprinciple }}" | base64
      
    - name: Id
      run: echo "${{ github.event.inputs.Id }}" | base64
